import React, { useState } from 'react';
import { AppState, UserProfile, MatchedJob } from './types';
import { matchJobsWithProfile, generateCoverLetter } from './services/geminiService';
import { generateN8nWorkflow } from './services/workflowGenerator';
import { generateWorkdayConsoleScript } from './services/workdayFiller';
import { Input, TextArea } from './components/Input';
import Button from './components/Button';
import JobCard from './components/JobCard';
import { Briefcase, ChevronRight, CheckCircle, Search, LogOut, AlertCircle, Mail, FileText, ArrowLeft, Save, User, Sparkles, Workflow, Bot, Loader2, FileCode, Download, MapPin, Globe } from 'lucide-react';

// Default initial state
const INITIAL_PROFILE: UserProfile = {
  name: "Alex Doe",
  email: "alex.doe@example.com",
  skills: ["React", "TypeScript", "Tailwind"],
  experience: "3 years",
  jobLocation: ["San Francisco", "New York"],
  workModes: ["Remote", "Hybrid"],
  primaryWorkMode: "Remote",
  preferredRoles: ["Frontend Developer"],
  resumeText: "Experienced Frontend Developer with 3 years of experience specializing in React, TypeScript, and modern CSS frameworks like Tailwind. Proven track record of building responsive web applications. Looking for remote opportunities.",
  coverLetter: "To Hiring Manager,\n\nI am writing to express my interest in the position. With my background in frontend development and passion for building user-centric applications, I am confident I can contribute effectively to your team.\n\nSincerely,\nAlex Doe",
  linkedin: "",
  portfolio: "",
  availability: "Immediate",
  salaryExpectation: "$80,000 - $100,000"
};

function App() {
  const [appState, setAppState] = useState<AppState>(AppState.LOGIN);
  const [profile, setProfile] = useState<UserProfile>(INITIAL_PROFILE);
  const [matchedJobs, setMatchedJobs] = useState<MatchedJob[]>([]);
  const [isMatching, setIsMatching] = useState(false);
  const [isGeneratingLetter, setIsGeneratingLetter] = useState(false);
  const [toast, setToast] = useState<{message: string, type: 'success' | 'error'} | null>(null);
  const [applyingJobs, setApplyingJobs] = useState<Set<string>>(new Set());
  const [appliedJobs, setAppliedJobs] = useState<Set<string>>(new Set());
  
  // New state for bot simulation
  const [activeBotJob, setActiveBotJob] = useState<string | null>(null);
  const [botStep, setBotStep] = useState<string>("");

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000); 
  };

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    setAppState(AppState.PROFILE);
  };

  const handleGenerateCoverLetter = async () => {
    setIsGeneratingLetter(true);
    try {
      const letter = await generateCoverLetter(profile);
      if (letter) {
        setProfile(prev => ({ ...prev, coverLetter: letter }));
        showToast("Cover letter auto-generated by AI!");
      }
    } catch (error) {
      showToast("Failed to generate cover letter.", "error");
    } finally {
      setIsGeneratingLetter(false);
    }
  };

  const handleDownloadN8n = () => {
    const workflowJson = generateN8nWorkflow(profile);
    const blob = new Blob([workflowJson], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `hirelift-n8n-workflow-${profile.name.replace(/\s+/g, '-').toLowerCase()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast("n8n Workflow downloaded! Import this into your n8n instance.");
  };

  const handleDownloadWorkdayScript = () => {
    const scriptContent = generateWorkdayConsoleScript(profile);
    const blob = new Blob([scriptContent], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `hirelift-workday-filler.js`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast("Workday Filler Script downloaded! Run this in Console (F12) on Workday sites.");
  };

  const handleProfileSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setAppState(AppState.APPLICATION_FORM);
    window.scrollTo(0, 0);

    // Automatically generate cover letter if it's the default or empty
    const isDefault = profile.coverLetter.startsWith("To Hiring Manager") || !profile.coverLetter || profile.coverLetter.length < 50;
    if (isDefault) {
      handleGenerateCoverLetter();
    }
  };

  const handleApplicationFormSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsMatching(true);
    try {
      const results = await matchJobsWithProfile(profile);
      setMatchedJobs(results.matched_jobs);
      setAppState(AppState.DASHBOARD);
      showToast(`Real-time search complete! Found ${results.matched_jobs.length} high-match jobs.`);
    } catch (err) {
      console.error(err);
      showToast("Failed to fetch real-time jobs. Please try again.", "error");
    } finally {
      setIsMatching(false);
    }
  };

  const getJobId = (job: MatchedJob) => `${job.company}-${job.job_title}`;

  const handleAutoApply = async (job: MatchedJob) => {
    const jobId = getJobId(job);
    setApplyingJobs(prev => new Set(prev).add(jobId));
    setActiveBotJob(jobId);

    // Dynamic steps based on company (Simulation)
    const isWorkday = ["Google", "Salesforce", "Walmart", "Target", "PwC"].includes(job.company) || job.company.includes("Group");
    
    const steps = isWorkday ? [
      `Connecting to ${job.company} Workday Portal...`,
      "Workday Detected: Initializing Filler Agent...",
      "Bypassing Login / SSO Redirect...",
      "Mapping Profile to 'legalNameSection'...",
      "Auto-Filling 'contactInformationSection'...",
      "Uploading Resume PDF to Workday Dropzone...",
      "Finalizing Application Review...",
    ] : [
      `Connecting to ${job.company} Career Portal...`,
      "AI Analyzing application form fields...",
      "Mapping Resume data to ATS fields...",
      "Filling Candidate Name, Email, LinkedIn...",
      "Uploading Resume PDF...",
      `Submitting Application to ${job.company}...`,
      "Waiting for confirmation..."
    ];

    // Simulate Bot Steps
    for (const step of steps) {
      setBotStep(step);
      await new Promise(resolve => setTimeout(resolve, 800 + Math.random() * 500)); 
    }

    setAppliedJobs(prev => new Set(prev).add(jobId));
    setApplyingJobs(prev => {
      const next = new Set(prev);
      next.delete(jobId);
      return next;
    });
    setActiveBotJob(null);
    setBotStep("");

    showToast(`Successfully applied to ${job.company}! Confirmation email sent to ${profile.email}.`);
  };

  const handleLogout = () => {
    setAppState(AppState.LOGIN);
    setMatchedJobs([]);
    setProfile(INITIAL_PROFILE);
    setAppliedJobs(new Set());
  };

  const handleBackFromApplication = () => {
    if (matchedJobs.length > 0) {
      setAppState(AppState.DASHBOARD);
    } else {
      setAppState(AppState.PROFILE);
    }
  };

  const handleWorkModeToggle = (mode: string) => {
    setProfile(prev => {
      const newModes = prev.workModes.includes(mode)
        ? prev.workModes.filter(m => m !== mode)
        : [...prev.workModes, mode];
      
      let newPrimary = prev.primaryWorkMode;
      if (!newModes.includes(newPrimary)) {
        newPrimary = newModes.length > 0 ? newModes[0] : '';
      }
      // If we just added a mode and there was no primary, make it primary
      if (newModes.length === 1 && !newPrimary) {
        newPrimary = newModes[0];
      }

      return {
        ...prev,
        workModes: newModes,
        primaryWorkMode: newPrimary
      };
    });
  };

  /* --- LOGIN SCREEN --- */
  if (appState === AppState.LOGIN) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 p-4">
        <div className="bg-white max-w-md w-full rounded-2xl shadow-xl p-8 border border-slate-100">
          <div className="text-center mb-8">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-100 text-blue-600 mb-4">
              <Briefcase size={32} />
            </div>
            <h1 className="text-3xl font-bold text-slate-900">HireLift</h1>
            <p className="text-slate-500 mt-2">Real-time AI job matching & auto-apply.</p>
          </div>
          
          <form onSubmit={handleLogin} className="space-y-6">
            <Input label="Full Name" type="text" placeholder="Alex Doe" required />
            <Input label="Email Address" type="email" placeholder="you@example.com" defaultValue="demo@hirelift.ai" required />
            <Input label="Password" type="password" placeholder="••••••••" defaultValue="password" required />
            
            <Button type="submit" className="w-full py-3 text-lg">
              Start Search
            </Button>
          </form>
          
          <p className="mt-6 text-center text-sm text-slate-400">
            Powered by Google Gemini 2.5
          </p>
        </div>
      </div>
    );
  }

  /* --- PROFILE SETUP (Step 1) --- */
  if (appState === AppState.PROFILE) {
    return (
      <div className="min-h-screen bg-slate-50 py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <div className="mb-8">
            <div className="flex items-center gap-2 text-sm font-semibold text-blue-600 mb-2">
              <span className="bg-blue-100 px-2 py-0.5 rounded">Step 1 of 2</span>
              <span>User Details</span>
            </div>
            <h1 className="text-3xl font-bold text-slate-900">Build Your Profile</h1>
            <p className="text-slate-500 mt-1">Tell us about your skills to find real-time matches.</p>
          </div>

          <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
            <div className="p-1 bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 h-1.5"></div>
            <form onSubmit={handleProfileSubmit} className="p-8 space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <Input 
                  label="Full Name" 
                  value={profile.name} 
                  onChange={e => setProfile({...profile, name: e.target.value})}
                />
                <Input 
                  label="Years of Experience" 
                  value={profile.experience} 
                  onChange={e => setProfile({...profile, experience: e.target.value})}
                  placeholder="e.g. 4 years"
                />
              </div>
              
              <Input 
                label="Preferred Roles (Comma separated)" 
                value={profile.preferredRoles.join(', ')} 
                onChange={e => setProfile({...profile, preferredRoles: e.target.value.split(',').map(s => s.trim())})}
                placeholder="e.g. Frontend Developer, UI Engineer"
              />
              
              <Input 
                label="Skills (Comma separated)" 
                value={profile.skills.join(', ')} 
                onChange={e => setProfile({...profile, skills: e.target.value.split(',').map(s => s.trim())})}
                placeholder="e.g. React, Node.js, Python"
              />

              {/* Enhanced Location Section */}
              <div className="bg-slate-50 p-5 rounded-lg border border-slate-200 space-y-4">
                <div className="flex items-center gap-2 text-slate-900 font-medium">
                  <MapPin size={18} className="text-blue-500" />
                  <h3>Job Preference</h3>
                </div>
                
                {/* Work Modes */}
                <div>
                  <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider block mb-2">Work Modes (Multi-select)</label>
                  <div className="flex flex-wrap gap-3">
                    {['Remote', 'Hybrid', 'Onsite'].map(mode => {
                       const isSelected = profile.workModes.includes(mode);
                       const isPrimary = profile.primaryWorkMode === mode;
                       return (
                        <div key={mode} className={`flex items-center gap-2 px-3 py-2 rounded-lg border transition-all ${isSelected ? 'bg-white border-blue-300 shadow-sm' : 'bg-slate-100 border-transparent opacity-70 hover:opacity-100'}`}>
                          <input 
                            type="checkbox" 
                            id={`mode-${mode}`}
                            checked={isSelected}
                            onChange={() => handleWorkModeToggle(mode)}
                            className="rounded text-blue-600 focus:ring-blue-500 h-4 w-4" 
                          />
                          <label htmlFor={`mode-${mode}`} className="text-sm font-medium text-slate-700 cursor-pointer select-none">
                            {mode}
                          </label>
                          
                          {isSelected && (
                             <button
                               type="button"
                               onClick={() => setProfile({...profile, primaryWorkMode: mode})}
                               className={`ml-2 text-[10px] px-2 py-0.5 rounded-full transition-colors font-bold uppercase tracking-wide ${isPrimary ? 'bg-blue-600 text-white' : 'bg-slate-200 text-slate-500 hover:bg-slate-300'}`}
                             >
                               {isPrimary ? 'Primary' : 'Set Primary'}
                             </button>
                          )}
                        </div>
                       );
                    })}
                  </div>
                  {profile.workModes.length === 0 && <p className="text-xs text-red-400 mt-1">Please select at least one work mode.</p>}
                </div>

                {/* Specific Locations */}
                <div>
                  <label className="text-xs font-semibold text-slate-500 uppercase tracking-wider block mb-2">Specific Cities / Countries (Optional)</label>
                  <div className="relative">
                    <Globe size={16} className="absolute left-3 top-3 text-slate-400" />
                    <input 
                      className="w-full pl-10 pr-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm"
                      value={profile.jobLocation.join(', ')} 
                      onChange={e => setProfile({...profile, jobLocation: e.target.value.split(',').map(s => s.trim())})}
                      placeholder="e.g. New York, London, Berlin"
                    />
                  </div>
                </div>
              </div>

              <TextArea 
                label="Resume Text (Paste content)" 
                value={profile.resumeText}
                onChange={e => setProfile({...profile, resumeText: e.target.value})}
                className="font-mono text-sm"
                placeholder="Paste the text content of your resume here..."
              />
              <div className="pt-4 border-t border-slate-100 flex justify-end">
                <Button type="submit" className="w-full md:w-auto px-8">
                  Next: Application Details <ChevronRight size={18} className="ml-2" />
                </Button>
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }

  /* --- APPLICATION FORM (Step 2) --- */
  if (appState === AppState.APPLICATION_FORM) {
    return (
      <div className="min-h-screen bg-slate-50 py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <Button 
            variant="ghost" 
            onClick={handleBackFromApplication} 
            className="mb-6 pl-0 hover:bg-transparent hover:text-blue-600"
          >
            <ArrowLeft size={20} className="mr-2" /> Back
          </Button>

          <div className="mb-8">
            <div className="flex items-center gap-2 text-sm font-semibold text-blue-600 mb-2">
              <span className="bg-blue-100 px-2 py-0.5 rounded">Step 2 of 2</span>
              <span>Application Form</span>
            </div>
            <h1 className="text-3xl font-bold text-slate-900">Master Application</h1>
            <p className="text-slate-500 mt-1">Configure your auto-apply email template.</p>
          </div>

          <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden">
            <div className="p-1 bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 h-1.5"></div>
            <form onSubmit={handleApplicationFormSubmit} className="p-8 space-y-6">
              
              <div className="bg-blue-50 p-4 rounded-lg border border-blue-100 mb-4">
                 <h3 className="font-semibold text-blue-900 mb-1">Email Configuration</h3>
                 <p className="text-sm text-blue-700 mb-4">Applications will be sent from this email address using your default mail client.</p>
                 <Input 
                    label="Your Email" 
                    type="email"
                    value={profile.email}
                    onChange={e => setProfile({...profile, email: e.target.value})}
                  />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 <Input 
                  label="LinkedIn URL" 
                  placeholder="https://linkedin.com/in/..." 
                  value={profile.linkedin || ''}
                  onChange={e => setProfile({...profile, linkedin: e.target.value})}
                />
                 <Input 
                  label="Portfolio / GitHub URL" 
                  placeholder="https://github.com/..." 
                  value={profile.portfolio || ''}
                  onChange={e => setProfile({...profile, portfolio: e.target.value})}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                 <Input 
                  label="Availability" 
                  placeholder="e.g. 2 weeks notice, Immediate" 
                  value={profile.availability || ''}
                  onChange={e => setProfile({...profile, availability: e.target.value})}
                />
                 <Input 
                  label="Salary Expectation" 
                  placeholder="e.g. $90k - $110k" 
                  value={profile.salaryExpectation || ''}
                  onChange={e => setProfile({...profile, salaryExpectation: e.target.value})}
                />
              </div>

              <div className="relative">
                <div className="flex justify-between items-end mb-1.5">
                  <label className="text-sm font-medium text-slate-700">Cover Letter (Template)</label>
                  <Button 
                    type="button"
                    variant="ghost" 
                    onClick={handleGenerateCoverLetter} 
                    isLoading={isGeneratingLetter}
                    className="text-xs h-8 px-2 text-blue-600 bg-blue-50 hover:bg-blue-100"
                  >
                    <Sparkles size={14} className="mr-1.5" /> 
                    {isGeneratingLetter ? 'Writing...' : 'Regenerate with AI'}
                  </Button>
                </div>
                <textarea
                  className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all min-h-[200px]"
                  placeholder="Dear Hiring Manager, I am excited to apply..."
                  value={profile.coverLetter || ''}
                  onChange={e => setProfile({...profile, coverLetter: e.target.value})}
                />
                <p className="text-xs text-slate-400 mt-1">AI will automatically create this based on your profile details.</p>
              </div>

              <div className="pt-4 border-t border-slate-100 flex justify-end gap-4">
                <Button type="submit" isLoading={isMatching} className="px-8 w-full md:w-auto">
                  {matchedJobs.length > 0 ? (
                    <span className="flex items-center gap-2"><Save size={18} /> Update & Find Real Jobs</span>
                  ) : (
                    <span className="flex items-center gap-2">Search Live Jobs <ChevronRight size={18} /></span>
                  )}
                </Button>
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }

  /* --- DASHBOARD --- */
  return (
    <div className="min-h-screen bg-slate-50 flex flex-col">
      <header className="bg-white border-b border-slate-200 sticky top-0 z-30">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-blue-600 text-white p-1.5 rounded-lg">
              <Briefcase size={20} />
            </div>
            <span className="font-bold text-xl tracking-tight text-slate-900">HireLift</span>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-sm font-medium text-slate-600 hidden md:block">Welcome, {profile.name}</span>
            <button onClick={handleLogout} className="text-slate-500 hover:text-slate-800 transition-colors">
              <LogOut size={20} />
            </button>
          </div>
        </div>
      </header>

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Sidebar */}
          <div className="lg:col-span-3 space-y-6">
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
              <h2 className="font-bold text-slate-900 mb-4">Your Profile</h2>
              <div className="space-y-4">
                <div>
                  <p className="text-xs text-slate-500 uppercase font-semibold">Role</p>
                  <p className="text-sm font-medium">{profile.preferredRoles[0]}</p>
                </div>
                <div>
                  <p className="text-xs text-slate-500 uppercase font-semibold">Experience</p>
                  <p className="text-sm font-medium">{profile.experience}</p>
                </div>
                <div>
                   <p className="text-xs text-slate-500 uppercase font-semibold">Location / Mode</p>
                   <p className="text-sm font-medium truncate" title={profile.jobLocation.join(', ')}>
                     {profile.jobLocation.length > 0 ? profile.jobLocation[0] : (profile.primaryWorkMode || 'Any')}
                     {profile.jobLocation.length > 1 && ` +${profile.jobLocation.length - 1}`}
                   </p>
                   <p className="text-xs text-slate-400 mt-1">
                     {profile.workModes.join(', ')}
                     {profile.primaryWorkMode && <span className="text-blue-500"> ({profile.primaryWorkMode} Pref)</span>}
                   </p>
                </div>
                <Button 
                  variant="outline" 
                  onClick={() => setAppState(AppState.PROFILE)} 
                  className="w-full text-sm mt-2"
                >
                  Edit Profile
                </Button>
              </div>
            </div>

            {/* n8n Automation Card */}
            <div className="bg-gradient-to-br from-indigo-900 to-purple-900 rounded-xl shadow-lg border border-indigo-700 p-6 text-white">
              <div className="flex items-center gap-2 mb-2">
                <Workflow size={20} className="text-pink-400" />
                <h3 className="font-bold">Automate with n8n</h3>
              </div>
              <p className="text-xs text-indigo-200 mb-4 leading-relaxed">
                Download a pre-configured workflow to automate applications on your own server.
              </p>
              <Button 
                onClick={handleDownloadN8n}
                className="w-full text-xs bg-white text-indigo-900 hover:bg-indigo-50 border-0"
              >
                Download Workflow JSON
              </Button>
            </div>

            {/* Workday Filler Card */}
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6">
              <div className="flex items-center gap-2 mb-2">
                <div className="p-1.5 bg-blue-100 text-blue-600 rounded-lg">
                  <FileCode size={18} />
                </div>
                <h3 className="font-bold text-slate-900 text-sm">Workday Filler</h3>
              </div>
              <p className="text-xs text-slate-500 mb-4">
                Get a smart script to auto-fill Workday applications in your browser console.
              </p>
              <Button 
                variant="outline"
                onClick={handleDownloadWorkdayScript}
                className="w-full text-xs flex items-center gap-2 justify-center"
              >
                <Download size={14} /> Get Script
              </Button>
            </div>

            <Button 
              onClick={() => setAppState(AppState.APPLICATION_FORM)} 
              className="w-full justify-between group shadow-sm"
              variant="outline"
            >
              <span className="flex items-center gap-2">
                <FileText size={16} /> Edit Application
              </span>
              <ChevronRight size={16} className="opacity-70 group-hover:translate-x-1 transition-transform" />
            </Button>
          </div>

          {/* Main Content Area */}
          <div className="lg:col-span-9">
            
            <div className="flex flex-col sm:flex-row items-center justify-between mb-6 gap-4">
              <h2 className="text-2xl font-bold text-slate-900">Live Job Matches ({'>75%'})</h2>
              <div className="text-sm text-slate-500 bg-white px-3 py-2 rounded-lg border border-slate-200 shadow-sm flex items-center gap-2">
                 <Search size={14} /> Found {matchedJobs.length} matches
              </div>
            </div>

            {/* Active Bot Overlay */}
            {activeBotJob && (
               <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm">
                 <div className="bg-white rounded-xl shadow-2xl p-8 max-w-sm w-full border border-slate-200 text-center animate-in zoom-in duration-300">
                    <div className="w-16 h-16 bg-blue-50 rounded-full flex items-center justify-center mx-auto mb-4 relative">
                       <Bot size={32} className="text-blue-600 relative z-10" />
                       <div className="absolute inset-0 rounded-full border-4 border-blue-100 border-t-blue-500 animate-spin"></div>
                    </div>
                    <h3 className="text-lg font-bold text-slate-900 mb-1">AI Auto-Pilot Running</h3>
                    <p className="text-sm text-slate-500 mb-4">Please wait while we apply for you.</p>
                    
                    <div className="bg-slate-50 rounded-lg p-3 text-sm font-mono text-blue-700 border border-blue-100 flex items-center gap-2 justify-center">
                      <Loader2 size={14} className="animate-spin" />
                      {botStep}
                    </div>
                 </div>
               </div>
            )}

            <div className="space-y-4">
              {matchedJobs.length > 0 ? (
                matchedJobs.map((job, index) => {
                  const jobId = getJobId(job);
                  return (
                    <JobCard 
                      key={index} 
                      job={job} 
                      onAutoApply={handleAutoApply}
                      isApplying={applyingJobs.has(jobId)}
                      isApplied={appliedJobs.has(jobId)}
                    />
                  );
                })
              ) : (
                <div className="text-center py-20 bg-white rounded-xl border border-slate-200 border-dashed">
                  <div className="mx-auto w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center text-slate-300 mb-4">
                    <Search size={32} />
                  </div>
                  <h3 className="text-lg font-medium text-slate-900">No matches found above 75%</h3>
                  <p className="text-slate-500 max-w-sm mx-auto mt-2">Try updating your profile or broadening your location preferences to find more real-time results.</p>
                  <Button 
                    variant="outline" 
                    onClick={() => setAppState(AppState.PROFILE)} 
                    className="mt-6"
                  >
                    Update Profile
                  </Button>
                </div>
              )}
            </div>
          </div>
        </div>
      </main>

      {/* Toast Notification */}
      {toast && (
        <div className={`fixed bottom-6 right-6 px-6 py-4 rounded-lg shadow-2xl text-white transform transition-all duration-300 translate-y-0 z-50 flex items-center gap-3 ${toast.type === 'success' ? 'bg-green-600' : 'bg-red-600'}`}>
          {toast.type === 'success' ? <CheckCircle size={20} /> : <AlertCircle size={20} />}
          <span className="font-medium">{toast.message}</span>
        </div>
      )}
    </div>
  );
}

export default App;