import { Job } from './types';

// A database of jobs with specific sources to test the new strict filtering rules
export const AVAILABLE_JOBS: Job[] = [
  // --- TECH GIANTS (MAANG) ---
  {
    id: 'mnc-google-01',
    job_title: "Software Engineer III, Frontend",
    company: "Google",
    location: "Mountain View, CA",
    required_skills: ["JavaScript", "TypeScript", "Angular", "Closure"],
    experience_required: "5+ years",
    job_source: "Company Career Page",
    description: "Build the next generation of Google Search interfaces.",
    is_verified: true,
  },
  {
    id: 'mnc-amazon-01',
    job_title: "SDE II - AWS Console",
    company: "Amazon Web Services",
    location: "Seattle, WA",
    required_skills: ["React", "Java", "AWS", "DynamoDB"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Develop scalable cloud management consoles for AWS.",
    is_verified: true,
  },
  {
    id: 'mnc-msft-01',
    job_title: "Senior Full Stack Developer",
    company: "Microsoft",
    location: "Redmond, WA",
    required_skills: ["C#", ".NET Core", "React", "Azure"],
    experience_required: "5+ years",
    job_source: "Company Career Page",
    description: "Join the Azure DevOps team to build developer tools.",
    is_verified: true,
  },
  {
    id: 'mnc-meta-01',
    job_title: "Product Designer",
    company: "Meta",
    location: "Menlo Park, CA",
    required_skills: ["Figma", "React", "Prototyping", "Interaction Design"],
    experience_required: "4+ years",
    job_source: "Company Career Page",
    description: "Design social experiences for billions of users.",
    is_verified: true,
  },
  {
    id: 'mnc-netflix-01',
    job_title: "Senior UI Engineer",
    company: "Netflix",
    location: "Los Gatos, CA",
    required_skills: ["React", "Node.js", "GraphQL", "Performance Optimization"],
    experience_required: "Senior",
    job_source: "Company Career Page",
    description: "Create cinematic TV interfaces for the web.",
    is_verified: true,
  },
  {
    id: 'mnc-apple-01',
    job_title: "Frontend Engineer - Apple TV+",
    company: "Apple",
    location: "Cupertino, CA",
    required_skills: ["JavaScript", "Ember.js", "HLS", "Video Streaming"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Build video streaming experiences for Apple TV.",
    is_verified: true,
  },

  // --- ENTERPRISE & FINTECH ---
  {
    id: 'mnc-salesforce-01',
    job_title: "Lead Member of Technical Staff",
    company: "Salesforce",
    location: "San Francisco, CA",
    required_skills: ["LWC", "JavaScript", "Apex", "Salesforce Platform"],
    experience_required: "7+ years",
    job_source: "Company Career Page",
    description: "Architect core CRM platform features.",
    is_verified: true,
  },
  {
    id: 'mnc-oracle-01',
    job_title: "Cloud UI Developer",
    company: "Oracle",
    location: "Austin, TX",
    required_skills: ["OJET", "JavaScript", "HTML5", "Rest APIs"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Build enterprise cloud dashboards.",
    is_verified: true,
  },
  {
    id: 'mnc-jpmc-01',
    job_title: "Associate, Software Engineering",
    company: "JPMorgan Chase",
    location: "New York, NY",
    required_skills: ["React", "Java Spring Boot", "Microservices"],
    experience_required: "2-4 years",
    job_source: "Company Career Page",
    description: "Modernize banking platforms for millions of customers.",
    is_verified: true,
  },
  {
    id: 'mnc-gs-01',
    job_title: "Vice President, Engineering",
    company: "Goldman Sachs",
    location: "New York, NY",
    required_skills: ["React", "TypeScript", "Java", "Financial Modeling"],
    experience_required: "6+ years",
    job_source: "Company Career Page",
    description: "High-frequency trading platform UI.",
    is_verified: true,
  },
  {
    id: 'mnc-stripe-01',
    job_title: "Frontend Engineer, Checkout",
    company: "Stripe",
    location: "Remote",
    required_skills: ["React", "Ruby", "TypeScript", "Payment APIs"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Optimize the world's best checkout flow.",
    is_verified: true,
  },
  {
    id: 'mnc-cisco-01',
    job_title: "Software Engineer IV",
    company: "Cisco",
    location: "San Jose, CA",
    required_skills: ["Python", "Networking", "Kubernetes", "Go"],
    experience_required: "5+ years",
    job_source: "Company Career Page",
    description: "Develop next-gen networking software.",
    is_verified: true,
  },
  {
    id: 'mnc-ibm-01',
    job_title: "AI Engineer",
    company: "IBM",
    location: "Armonk, NY",
    required_skills: ["Python", "TensorFlow", "Watson", "Cloud"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Integrate Watson AI into enterprise solutions.",
    is_verified: true,
  },

  // --- CONSULTING & SERVICES (Heavily on Superset/Naukri) ---
  {
    id: 'mnc-accenture-01',
    job_title: "Custom App Development Manager",
    company: "Accenture",
    location: "Chicago, IL",
    required_skills: ["Angular", "Cloud Architecture", "Agile", "Team Lead"],
    experience_required: "8+ years",
    job_source: "Naukri",
    description: "Lead digital transformation projects for Fortune 500 clients.",
    is_verified: true,
  },
  {
    id: 'mnc-deloitte-01',
    job_title: "Solutions Architect",
    company: "Deloitte",
    location: "London, UK",
    required_skills: ["AWS", "Python", "React", "System Design"],
    experience_required: "5+ years",
    job_source: "LinkedIn",
    description: "Architect scalable solutions for public sector clients.",
    is_verified: true,
  },
  {
    id: 'mnc-tcs-01',
    job_title: "System Engineer",
    company: "TCS",
    location: "Mumbai, India",
    required_skills: ["Java", "J2EE", "SQL", "Unix"],
    experience_required: "2+ years",
    job_source: "Superset",
    description: "Core banking solution maintenance and upgrades.",
    is_verified: true,
  },
  {
    id: 'mnc-infosys-01',
    job_title: "Technology Analyst",
    company: "Infosys",
    location: "Bangalore, India",
    required_skills: ["React", "Node.js", "MongoDB", "Express"],
    experience_required: "3+ years",
    job_source: "Naukri",
    description: "MERN stack development for retail clients.",
    is_verified: true,
  },
  {
    id: 'mnc-wipro-01',
    job_title: "Project Engineer",
    company: "Wipro",
    location: "Hyderabad, India",
    required_skills: ["Python", "Django", "AWS", "REST API"],
    experience_required: "2-4 years",
    job_source: "Superset",
    description: "Backend development for healthcare clients.",
    is_verified: true,
  },
  {
    id: 'mnc-hcl-01',
    job_title: "Senior Developer",
    company: "HCL Tech",
    location: "Noida, India",
    required_skills: ["Java", "Spring Boot", "Microservices"],
    experience_required: "5+ years",
    job_source: "Naukri",
    description: "Enterprise software development for banking sector.",
    is_verified: true,
  },
  {
    id: 'mnc-cognizant-01',
    job_title: "Programmer Analyst",
    company: "Cognizant",
    location: "Chennai, India",
    required_skills: ["C#", ".NET", "SQL Server", "Azure"],
    experience_required: "3+ years",
    job_source: "LinkedIn",
    description: "Developing insurance claim processing systems.",
    is_verified: true,
  },
  {
    id: 'mnc-capgemini-01',
    job_title: "Senior Consultant",
    company: "Capgemini",
    location: "Pune, India",
    required_skills: ["Salesforce", "Apex", "Visualforce", "LWC"],
    experience_required: "6+ years",
    job_source: "Superset",
    description: "CRM implementation for automotive clients.",
    is_verified: true,
  },
  {
    id: 'mnc-techm-01',
    job_title: "Software Engineer",
    company: "Tech Mahindra",
    location: "Pune, India",
    required_skills: ["Java", "Telecom Domain", "Spring"],
    experience_required: "3+ years",
    job_source: "Naukri",
    description: "5G network slicing software development.",
    is_verified: true,
  },

  // --- TECH INNOVATORS ---
  {
    id: 'mnc-tesla-01',
    job_title: "Software Engineer, Autopilot",
    company: "Tesla",
    location: "Palo Alto, CA",
    required_skills: ["C++", "Python", "Computer Vision", "React"],
    experience_required: "4+ years",
    job_source: "Company Career Page",
    description: "Build internal tools for Autopilot data labeling.",
    is_verified: true,
  },
  {
    id: 'mnc-uber-01',
    job_title: "Web Engineer, Uber Eats",
    company: "Uber",
    location: "San Francisco, CA",
    required_skills: ["Fusion.js", "React", "Node.js", "Go"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Enhance the Uber Eats web ordering experience.",
    is_verified: true,
  },
  {
    id: 'mnc-airbnb-01',
    job_title: "Frontend Engineer, Design Systems",
    company: "Airbnb",
    location: "Remote",
    required_skills: ["React", "TypeScript", "Accessibility", "CSS"],
    experience_required: "4+ years",
    job_source: "Company Career Page",
    description: "Maintain and evolve the Airbnb Design Language System (DLS).",
    is_verified: true,
  },
  {
    id: 'mnc-spotify-01',
    job_title: "Web Developer",
    company: "Spotify",
    location: "Stockholm, Sweden",
    required_skills: ["React", "Next.js", "TypeScript", "TDD"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Build the Spotify Web Player experience.",
    is_verified: true,
  },

  // --- AUTOMOTIVE & INDUSTRY ---
  {
    id: 'mnc-bmw-01',
    job_title: "Connected Car Developer",
    company: "BMW Group",
    location: "Munich, Germany",
    required_skills: ["Android", "Kotlin", "Java", "IoT"],
    experience_required: "4+ years",
    job_source: "Company Career Page",
    description: "Develop in-car infotainment apps.",
    is_verified: true,
  },
  {
    id: 'mnc-siemens-01',
    job_title: "Industrial Edge Developer",
    company: "Siemens",
    location: "Berlin, Germany",
    required_skills: ["C++", "Linux", "Docker", "Python"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Edge computing solutions for factories.",
    is_verified: true,
  },
  {
    id: 'mnc-ge-01',
    job_title: "Software Engineer",
    company: "General Electric",
    location: "Boston, MA",
    required_skills: ["Java", "Predix", "Cloud Foundry"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Industrial IoT platform development.",
    is_verified: true,
  },

  // --- EXPANDED GLOBAL MNCs (Semiconductors, Retail, Media, Finance) ---
  {
    id: 'mnc-nvidia-01',
    job_title: "Senior Deep Learning Engineer",
    company: "NVIDIA",
    location: "Santa Clara, CA",
    required_skills: ["C++", "CUDA", "PyTorch", "Python"],
    experience_required: "5+ years",
    job_source: "Company Career Page",
    description: "Optimize AI models for next-gen GPU architectures.",
    is_verified: true,
  },
  {
    id: 'mnc-walmart-01',
    job_title: "Staff Software Engineer, Backend",
    company: "Walmart Global Tech",
    location: "Bentonville, AR",
    required_skills: ["Java", "Spring Boot", "Kafka", "Cassandra"],
    experience_required: "6+ years",
    job_source: "Company Career Page",
    description: "Build high-scale systems for the world's largest retailer.",
    is_verified: true,
  },
  {
    id: 'mnc-morganstanley-01',
    job_title: "VP, Technology Associate",
    company: "Morgan Stanley",
    location: "New York, NY",
    required_skills: ["Java", "Angular", "Kubernetes", "SQL"],
    experience_required: "5-8 years",
    job_source: "LinkedIn",
    description: "Develop wealth management trading platforms.",
    is_verified: true,
  },
  {
    id: 'mnc-adobe-01',
    job_title: "Computer Scientist",
    company: "Adobe",
    location: "San Jose, CA",
    required_skills: ["C++", "Machine Learning", "Image Processing"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Enhance creative tools within Photoshop and Illustrator.",
    is_verified: true,
  },
  {
    id: 'mnc-visa-01',
    job_title: "Staff Software Engineer",
    company: "Visa",
    location: "Foster City, CA",
    required_skills: ["Go", "Docker", "Microservices", "REST"],
    experience_required: "5+ years",
    job_source: "Company Career Page",
    description: "Architect secure payment processing gateways.",
    is_verified: true,
  },
  {
    id: 'mnc-disney-01',
    job_title: "Streaming Media Engineer",
    company: "Disney+",
    location: "Burbank, CA",
    required_skills: ["C++", "AWS", "Video Encoding", "Python"],
    experience_required: "4+ years",
    job_source: "Company Career Page",
    description: "Optimize video delivery for millions of Disney+ subscribers.",
    is_verified: true,
  },
  {
    id: 'mnc-samsung-01',
    job_title: "Android Framework Engineer",
    company: "Samsung Research",
    location: "Mountain View, CA",
    required_skills: ["Java", "Kotlin", "Android SDK", "AOSP"],
    experience_required: "3+ years",
    job_source: "LinkedIn",
    description: "Develop core features for Samsung Galaxy devices.",
    is_verified: true,
  },
  {
    id: 'mnc-nike-01',
    job_title: "Senior Full Stack Engineer",
    company: "Nike",
    location: "Beaverton, OR",
    required_skills: ["React", "Node.js", "AWS", "GraphQL"],
    experience_required: "4+ years",
    job_source: "Company Career Page",
    description: "Build immersive e-commerce experiences for Nike.com.",
    is_verified: true,
  },
  {
    id: 'mnc-intel-01',
    job_title: "Firmware Engineer",
    company: "Intel",
    location: "Portland, OR",
    required_skills: ["C", "C++", "Assembly", "Embedded Systems"],
    experience_required: "2+ years",
    job_source: "Company Career Page",
    description: "Develop low-level firmware for next-gen processors.",
    is_verified: true,
  },
  {
    id: 'mnc-pfizer-01',
    job_title: "Senior Data Scientist",
    company: "Pfizer",
    location: "New York, NY",
    required_skills: ["Python", "R", "SQL", "Bioinformatics"],
    experience_required: "4+ years",
    job_source: "LinkedIn",
    description: "Analyze clinical trial data to accelerate drug discovery.",
    is_verified: true,
  },
  {
    id: 'mnc-ey-01',
    job_title: "Technology Consultant - Cloud",
    company: "EY",
    location: "London, UK",
    required_skills: ["Azure", "Terraform", "DevOps", "Consulting"],
    experience_required: "3+ years",
    job_source: "Superset",
    description: "Advise enterprise clients on cloud migration strategies.",
    is_verified: true,
  },
  {
    id: 'mnc-verizon-01',
    job_title: "Network Software Engineer",
    company: "Verizon",
    location: "Basking Ridge, NJ",
    required_skills: ["Python", "SDN", "Networking", "Cisco"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Automate 5G network infrastructure deployment.",
    is_verified: true,
  },
  {
    id: 'mnc-shell-01',
    job_title: "DevOps Engineer",
    company: "Shell",
    location: "Houston, TX",
    required_skills: ["Azure", "Kubernetes", "CI/CD", "Python"],
    experience_required: "4+ years",
    job_source: "LinkedIn",
    description: "Support renewable energy trading platforms.",
    is_verified: true,
  },
  {
    id: 'mnc-sony-01',
    job_title: "Graphics Programmer",
    company: "PlayStation (Sony)",
    location: "San Mateo, CA",
    required_skills: ["C++", "DirectX", "Vulkan", "Shader Programming"],
    experience_required: "3+ years",
    job_source: "Company Career Page",
    description: "Push the boundaries of graphics on PlayStation consoles.",
    is_verified: true,
  },
  {
    id: 'mnc-pg-01',
    job_title: "Data Analytics Manager",
    company: "P&G",
    location: "Cincinnati, OH",
    required_skills: ["SQL", "Tableau", "Power BI", "Python"],
    experience_required: "5+ years",
    job_source: "Naukri",
    description: "Drive supply chain efficiency through data analytics.",
    is_verified: true,
  },

  // --- MISC ---
  {
    id: 'j1',
    job_title: "Senior Frontend Engineer",
    company: "TechFlow Solutions",
    location: "Remote",
    required_skills: ["React", "TypeScript", "Tailwind CSS", "Redux"],
    experience_required: "4+ years",
    job_source: "LinkedIn",
    description: "Building next-gen SaaS dashboards.",
    is_verified: true,
  },
  {
    id: 'j2',
    job_title: "Full Stack Developer",
    company: "Innovate Inc",
    location: "Hybrid - New York",
    required_skills: ["Node.js", "React", "PostgreSQL", "AWS"],
    experience_required: "2-5 years",
    job_source: "LinkedIn",
    description: "Full cycle development for our e-commerce platform.",
    is_verified: true,
  },
  {
    id: 'j3',
    job_title: "UI/UX Designer",
    company: "Creative Studio",
    location: "Remote",
    required_skills: ["Figma", "Adobe XD", "Prototyping", "HTML/CSS"],
    experience_required: "3 years",
    job_source: "Naukri",
    description: "Design intuitive user interfaces for mobile apps.",
    is_verified: true,
  },
  {
    id: 'j4',
    job_title: "Backend Engineer",
    company: "DataSystems",
    location: "Austin, TX",
    required_skills: ["Python", "Django", "Docker", "Kubernetes"],
    experience_required: "3-6 years",
    job_source: "Superset",
    description: "Scaling our data processing pipelines.",
    is_verified: true,
  }
];

export const SYSTEM_PROMPT = `
You are an advanced AI Job Intelligence Engine for a platform called "HireLift".
HireLift is a trusted job application platform that provides ONLY genuine, verified job opportunities.

Your responsibility is to:
- Analyze user profiles
- Match jobs accurately based on skills and experience
- Rank jobs by relevance
- FILTER jobs strictly by source

CORE AI TASKS:
1. Resume Skill Extraction: Extract skills, experience, role fit, and strengths from resume_text.
2. Job Matching Logic: Match jobs based on skill overlap (highest priority), experience compatibility, location preference, and role relevance.
3. Matching Score Calculation: Generate a matching percentage (0–100). Show only jobs with 60%+ match.
4. Job Ranking: Sort jobs from highest to lowest match score.

5. STRICT SOURCE VERIFICATION RULE (CRITICAL):
   - You must ONLY recommend jobs where the 'job_source' is one of the following:
     a) "Naukri"
     b) "LinkedIn"
     c) "Company Career Page"
     d) "Superset"
   - DO NOT recommend jobs from "Craigslist", "Third Party", "Agencies", or generic job boards.
   - If a job matches skills but the source is not allowed, DO NOT include it in the output.

6. Auto Apply Readiness: Identify if user profile is suitable for auto-apply.

OUTPUT FORMAT:
Return results in JSON format only.
{
  "matched_jobs": [
    {
      "job_title": "String",
      "company": "String",
      "location": "String",
      "match_percentage": Number,
      "matched_skills": ["String"],
      "missing_skills": ["String"],
      "auto_apply_eligible": Boolean,
      "apply_url": "String"
    }
  ]
}
`;